apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCGgnVRR1tz+gTSkkozWQHQKk4tNi5M2bZEhdiGS0wtnh92zt+1k4kLlE6KMjBSYsWbN7+dZpSO0BTM+b9/IVn2WYZG3HxTK67vgNe/Nv30JFJSTO3QN4FyK5pAlSjJ3n3A/BfmDGZSMuFSGO9EhBNyn0Gnd9rd4Fzdn/Guf5Ym5jB1DYQCrJfR3VvIkO+QuH66xP+ODkFx/MBofS4JC0Pxa0NXgJ+4+FcYSw9JpnWff8jRA57pb1Eq4QIbz3Na9fD1D1uN4sBycQ5eF4NSmvQHYK4yx3AKqeIpvEMJvzagOmsFcWvX8YtRvQ6jcnfMJZsbVzrQs6J9Im8uWAfOTdtf2NOPbSM9+xgkD2nh5yuNHcVYVmBzSZq1GD8fdo7PxNwfr1WvXc8YHJZ/cA8XQYcrjaMAgWm9ncxc9PS2U1BBZWrgeL06rOmSY/Uzoez53NR85Vt2JfQ/yEgZWG4AdKNi971urc/f9+P+JFyx1pltdFFSqMxaG7SN1YalMSAxzmc47HfKU7F7hNPt6d83N7Oxo+ENT2fthd9R7pX0qlTkkAl8l1ROtjsGq0H5CIDlDg1OHD6xOIHNlaSXtPeeuV38Airnr/e6T3hfF5DR32UdFMWt2x/uPjp9QkLTiJPACZncFqbCzmsqX+fCRERlHOt8O9nFTkrxaIFRqEXKwWc8YQgXpG7UPxOtVgXN/r6C+bv6NfqOaZWNL+g7VQcy/Gf2CLs6UA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
