apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB6iexlFxGc4JTyse0AV91qFghSEj8/T39moqiNeNqTS1Q8Fm7EWUF1G/8vrC9bxDuCmjpR8/FomyJVz1nwggGDzqsG4x8iNMCJyYe7/NVvDYGq6fMa3u/am5ZkHsSA0PjxPG7a1vKBZQlZCECjOyvsFIJpWFpfja/iLSGTPnAF8Rk3UoQYvl991jhpoanhrmD7vHqOBb8iJmHN4WuG50x0NBkDxRgWmPK8XupmLzS4dEFRPqwETLX5SuR91LxCojKCXCBokVTJDhmJ9cvfI+TAVwGNcdaPFnffFgmn/gzEITqUtndq5KKVsj6qJn/jKZMvP8EPNqnMgE7mP6kEyOSMYKFmwjWcqx8PIwisPgkVOzDXhZNSnFWZ2wCTUkIy2U5SgnGzOCB5hYkDSysS2OHzGol3JkzLqCFfKKu4zulFTgSptXtGWFiraFFt8wlH6CrmWLKhaLImoShaozrAc0EcRAZCylqFZMHZUWwgix4A5LQPH/2LLzNMP4Pk740NUoIKQsrycZKlcFqIvEsOkRTljU/iLXkcxo54y4yTckT+RIZQFhWYY12l+3ybfPf3Bad2RpmLQa634GQiS5Hz1nbf1Ji7INnQywAlfrji/0+/yiu7kEMAM61u1+uiINtTZKwIde9X6hOzkXTQs3PjXZ4JXMnMI5wPg94Dh09Qhv/X44j4FawTC6/rNp2ZX5WLyyR6nT/KgYxjQVDaqEefoS4i1AvVsw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
